using System.Text;
using Ferrum.Codegen.Models;

namespace Ferrum.Codegen.Emitter;

/// <summary>
/// Emits C# source code containing <c>[LibraryImport]</c> bindings and
/// <c>[StructLayout]</c> declarations derived from a <see cref="ParsedHeader"/>.
/// </summary>
/// <remarks>
/// Generated code is NativeAOT-compatible:
/// <list type="bullet">
///   <item>Uses <c>[LibraryImport]</c> (source-generated) instead of <c>[DllImport]</c></item>
///   <item>All structs use <c>[StructLayout(LayoutKind.Sequential)]</c></item>
///   <item>No <c>MarshalAs</c> attributes (not AOT-safe for all types)</item>
///   <item>Pointer parameters and unsafe contexts are explicit</item>
/// </list>
/// </remarks>
public sealed class BindingEmitter
{
    private readonly EmitterOptions _options;

    public BindingEmitter(EmitterOptions options) => _options = options;

    /// <summary>
    /// Generates the complete C# source text for the given
    /// <paramref name="header"/>.
    /// </summary>
    public string Emit(ParsedHeader header)
    {
        var sb = new StringBuilder();

        WriteFileHeader(sb, header);
        WriteUsings(sb);
        WriteNamespaceOpen(sb);

        if (header.Structs.Count > 0)
        {
            foreach (var s in header.Structs)
                WriteStruct(sb, s);
            sb.AppendLine();
        }

        if (header.Functions.Count > 0)
        {
            WriteBindingClassOpen(sb);
            foreach (var fn in header.Functions)
                WriteFunction(sb, fn);
            WriteBindingClassClose(sb);
        }

        WriteNamespaceClose(sb);
        return sb.ToString();
    }

    // -----------------------------------------------------------------------
    // File-level boilerplate
    // -----------------------------------------------------------------------

    private void WriteFileHeader(StringBuilder sb, ParsedHeader header)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by ferrum-codegen — DO NOT EDIT.");
        if (!string.IsNullOrEmpty(header.SourceFile))
            sb.AppendLine($"// Source: {System.IO.Path.GetFileName(header.SourceFile)}");
        sb.AppendLine($"// Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    private static void WriteUsings(StringBuilder sb)
    {
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
    }

    private void WriteNamespaceOpen(StringBuilder sb)
    {
        sb.AppendLine($"namespace {_options.Namespace};");
        sb.AppendLine();
    }

    private static void WriteNamespaceClose(StringBuilder sb)
    {
        // File-scoped namespace — nothing to close
    }

    // -----------------------------------------------------------------------
    // Struct emission
    // -----------------------------------------------------------------------

    private static void WriteStruct(StringBuilder sb, StructDecl s)
    {
        sb.AppendLine("/// <summary>Auto-generated blittable struct.</summary>");
        sb.AppendLine("[StructLayout(LayoutKind.Sequential)]");
        sb.AppendLine($"public unsafe struct {s.Name}");
        sb.AppendLine("{");
        foreach (var f in s.Fields)
        {
            sb.AppendLine($"    public {f.Type} {f.Name};");
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    // -----------------------------------------------------------------------
    // Function binding emission
    // -----------------------------------------------------------------------

    private void WriteBindingClassOpen(StringBuilder sb)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated [LibraryImport] bindings.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"internal static unsafe partial class {_options.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine($"    private const string LibraryName = \"{_options.LibraryName}\";");
        sb.AppendLine();
    }

    private static void WriteBindingClassClose(StringBuilder sb)
    {
        sb.AppendLine("}");
    }

    private static void WriteFunction(StringBuilder sb, FunctionDecl fn)
    {
        sb.AppendLine($"    /// <summary>Binding for <c>{fn.Name}</c>.</summary>");
        sb.AppendLine("    [LibraryImport(LibraryName)]");
        sb.AppendLine($"    internal static partial {fn.ReturnType} {fn.Name}({BuildParamList(fn.Parameters)});");
        sb.AppendLine();
    }

    private static string BuildParamList(IReadOnlyList<ParameterDecl> parameters)
    {
        if (parameters.Count == 0) return string.Empty;
        return string.Join(", ", parameters.Select(p => $"{p.Type} {p.Name}"));
    }
}

/// <summary>Options controlling the output of <see cref="BindingEmitter"/>.</summary>
public sealed class EmitterOptions
{
    /// <summary>C# namespace for generated types.</summary>
    public string Namespace   { get; set; } = "Ferrum.Generated";

    /// <summary>Name of the partial class that holds the [LibraryImport] methods.</summary>
    public string ClassName   { get; set; } = "NativeBindings";

    /// <summary>
    /// Value passed as the first argument to <c>[LibraryImport]</c>.
    /// On iOS use <c>"__Internal"</c>; on Android use the bare .so name.
    /// </summary>
    public string LibraryName { get; set; } = "__Internal";
}
