using System.Runtime.InteropServices;
using Ferrum.Framework.Interop;

namespace MinimalDemo.Interop;

/// <summary>
/// Hand-wired [LibraryImport] binding for the Ferrum test stub.
///
/// This file was generated by running:
///   ferrum-codegen --input native/test_stub/include/add.h \
///                  --output samples/MinimalDemo/Interop/AddInterop.cs \
///                  --ns MinimalDemo.Interop \
///                  --class AddInterop \
///                  --lib __Internal
///
/// It is checked in for reference and to keep the sample self-contained.
/// In a real project, regenerate this file when the C header changes.
/// </summary>
internal static unsafe partial class AddInterop
{
    // On iOS (NativeAOT) all code is statically linked — use __Internal.
    // On Android the symbol comes from libferrum_test_stub.so.
    [LibraryImport(InteropConstants.FerrumLibrary)]
    internal static partial int ferrum_add(int a, int b);
}
